FROM python:3.7
WORKDIR /app
ENV FLASK_APP ./app
ENV FLASK_RUN_HOST 0.0.0.0
RUN apt-get update && apt-get install --assume-yes apt-utils
RUN apt-get install -y gcc musl-dev nano
COPY ./docker/flask/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./flask_app .
CMD ["flask", "run"]
