version: '3.5'
services:
  web_flask:
    container_name: flask_api
    image: maksim1990/flask_rest_api_service:latest
    networks:
      - docker-shared-services
      - net
    volumes:
      - ./env/.env.dist:/app/.env
    ports:
      - "${APP_HTTP_PORT}:5000"
    environment:
      FLASK_ENV: development

  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    networks:
      - docker-shared-services
      - net
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "${APP_MONGO_PORT}:27017"

networks:
  docker-shared-services:
    external: true
  net:
    driver: bridge