version: '3.5'
services:
  web_flask:
    container_name: flask_api
    image: maksim1990/flask_rest_api_service:latest
    ports:
      - "${APP_HTTP_PORT}:5000"
    environment:
      FLASK_ENV: development
    networks:
      - docker-shared-services
      - net
    volumes:
      - ./env/.env.dist:/app/.env
    depends_on:
        - mysql

  mysql:
    image: mysql:5.7.21
    networks:
      - net
    environment:
        - MYSQL_ROOT_PASSWORD=${APP_MYSQL_PASSWORD}
        - MYSQL_DATABASE=${APP_MYSQL_DATABASE}
    ports:
         - "${APP_MYSQL_PORT}:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql

    mongodb:
      image: mongo:latest
      container_name: mongodb_service
      networks:
        - docker-shared-services
        - net
      #restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASSWORD}
      volumes:
        - ./data/mongo:/data/db
      ports:
        - "${APP_MONGO_PORT}:27017"

networks:
  docker-shared-services:
    external: true
  net:
    driver: bridge