version: '3.5'
services:
  web_flask:
    container_name: flask_api
    image: maksim1990/flask_rest_api_service:latest
    ports:
      - "${APP_HTTP_PORT}:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./env:/var/www/env
    depends_on:
        - mysql

  mysql:
    image: mysql:5.7.21
    environment:
        - MYSQL_ROOT_PASSWORD=flask
        - MYSQL_DATABASE=flaskDB
    ports:
         - "${APP_MYSQL_PORT}:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
