version: '3.7'
services:
  web_flask:
    container_name: flask_api
    image: maksim1990/flask_rest_api_service:latest
    networks:
      - docker-shared-services
    ports:
      - "${APP_HTTP_PORT}:5000"
    environment:
      FLASK_ENV: development
